### ISSUE TITLE
Ruff extension error while trying to find the Ruff binary in VS Code.

### ISSUE THREAD

**Issue by krave1986** [astral-sh/ruff-vscode#696]
### Description

After upgrading Python to 3.13.2 from 3.12.4, this error occurs every time I open VS Code.
Do you have any suggestions on how to avoid this?

Here is the log of the extension:

> 2025-02-10 09:20:47.589 [info] Name: Ruff
> 2025-02-10 09:20:47.589 [info] Module: ruff
> 2025-02-10 09:20:47.589 [info] Python extension loading
> 2025-02-10 09:20:47.589 [info] Waiting for interpreter from python extension.
> 2025-02-10 09:20:47.596 [info] Python extension loaded
> 2025-02-10 09:20:47.605 [info] Using interpreter: d:\learn\Python\learn-python-in-vscode\Libs\Psycopg 3\Official\Getting started with Psycopg 3\.venv\Scripts\python.exe
> 2025-02-10 09:20:48.635 [error] Error while trying to find the Ruff binary: Error: Traceback (most recent call last):
>   File "c:\Users\Administrator\.vscode\extensions\charliermarsh.ruff-2025.6.0-win32-x64\bundled\tool\find_ruff_binary_path.py", line 3, in <module>
>     import sysconfig
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\sysconfig\__init__.py", line 5, in <module>
>     import threading
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 35, in <module>
>     _start_joinable_thread = _thread.start_joinable_thread
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: module '_thread' has no attribute 'start_joinable_thread'
> 
> 2025-02-10 09:20:49.377 [info] Falling back to bundled executable: c:\Users\Administrator\.vscode\extensions\charliermarsh.ruff-2025.6.0-win32-x64\bundled\libs\bin\ruff.exe

**Comment by dhruvmanila** [comment]
I don't think that this is related to the Ruff extension. My guess is that the `PYTHONHOME` still points to 3.13 and so when invoking the `python` executable inside the `py_3_12_6` environment, it's using the 3.12 executable on a standard library of 3.13 (https://docs.python.org/3/using/cmdline.html#envvar-PYTHONHOME).

I'm going to close this issue as it's not actionable on our end but feel free to ask any other questions.

**Comment by krave1986** [comment]
Thanks for your help!  Removing the `PYTHONHOME` environment variable did the trick. Everything seems to be working fine now.
